name: Hello World

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Version to deploy"
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a specific variable
        run: echo hello '${{github.event.commits[0].author.name}}'
      - name: Print all of the github variables
        run: echo start '${{toJSON(github)}}'
      - name: Print a repository secret
        run: echo start '${{ secrets.SUPER_SECRET }}'
      - name: Print an Environment secret
        run: echo start '${{ secrets.SUPER_SECRET_ENV }}'
      - name: Print an environment variable
        run: echo start '${{ vars.PRODUCTION_VAR1 }}'
      - name: Print a repository variable:
        run: echo start '${{ vars.REPO_VAR1 }}'

        
        #      - name: First interaction
#        uses: actions/first-interaction@v1.3.0
#        with:
#          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
#          repo-token:
#          # Comment to post on an individual's first issue
#          issue-message: # optional
#          # Comment to post on an individual's first pull request
#          pr-message: # optional
