name: Hello World

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Version to deploy"
        required: true
        type: string


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
